# -*- mode: python ; coding: utf-8 -*-
"""PyInstaller spec for the **Designer + Runner** build (no Hub).

Output (after ``build_studio.ps1`` merges staging + vendor)::

    dist/Macro2k-Studio/
        Macro2k.exe      -> Designer (default) + Runner (--runner)
        _macro2k/        -> private runtime files
        vendor/          -> adb / scrcpy / frida (external, not bundled)

The lean sibling of ``apps_build.spec``: same entry
(``packaging/entry_studio.py``, which dispatches on ``--designer`` /
``--runner``) and the same runtime payload, minus the Hub — ``web/hub`` is not
bundled and ``workflow_hub`` is never analysed. Reaching the Designer is
``Macro2k.exe`` with no switch, or ``Macro2k.exe --designer [flow.json]``.

``vendor/`` stays external/updatable, exactly like the full build. Prefer
``build_studio.ps1`` (handles staging + vendor). Raw build::

    pyinstaller --noconfirm --clean packaging/apps_studio.spec
"""
import os
import sys

from PyInstaller.utils.hooks import collect_all, collect_submodules

ROOT = os.path.dirname(SPECPATH)  # SPECPATH = .../packaging
APPS = os.path.join(ROOT, "apps")

# --- app icon -----------------------------------------------------------------
# packaging/app.ico is generated by ``python packaging/make_icon.py`` (Pillow).
# Absent (fresh clone that skipped that step) -> build without a custom icon
# rather than failing.
_icon = os.path.join(SPECPATH, "app.ico")
ICON = _icon if os.path.isfile(_icon) else None

# --- app version → Windows .exe version resource -----------------------------
# Single source of truth is src/version.py; mirror it into the PE metadata so
# right-click → Properties → Details shows the version on the packaged .exe.
if ROOT not in sys.path:
    sys.path.insert(0, ROOT)
from src.version import APP_NAME, __version__, version_tuple  # noqa: E402

_vt = (version_tuple() + (0, 0, 0, 0))[:4]  # pad to the 4 ints Windows wants
from PyInstaller.utils.win32.versioninfo import (  # noqa: E402
    VSVersionInfo, FixedFileInfo, StringFileInfo, StringTable, StringStruct, VarFileInfo, VarStruct,
)
version_info = VSVersionInfo(
    ffi=FixedFileInfo(filevers=_vt, prodvers=_vt, mask=0x3F, flags=0x0,
                      OS=0x40004, fileType=0x1, subtype=0x0, date=(0, 0)),
    kids=[
        StringFileInfo([StringTable("040904B0", [
            StringStruct("CompanyName", APP_NAME),
            StringStruct("FileDescription", f"{APP_NAME} — Designer + Runner"),
            StringStruct("FileVersion", __version__),
            StringStruct("InternalName", APP_NAME),
            StringStruct("OriginalFilename", f"{APP_NAME}.exe"),
            StringStruct("ProductName", APP_NAME),
            StringStruct("ProductVersion", __version__),
        ])]),
        VarFileInfo([VarStruct("Translation", [0x409, 1200])]),
    ],
)

# --- third-party collection (pywebview EdgeChromium backend via pythonnet) ---
datas = []
binaries = []
hiddenimports = []
for _pkg in ("webview", "clr_loader", "pythonnet"):
    try:
        _d, _b, _h = collect_all(_pkg)
        datas += _d
        binaries += _b
        hiddenimports += _h
    except Exception:
        pass

# pure-python-adb installs as the ``ppadb`` package; pull all submodules since
# clients/connections are imported dynamically.
hiddenimports += collect_submodules("ppadb")
hiddenimports += [
    "clr",            # pythonnet entry module
    "bottle",         # pywebview's local http server
    "proxy_tools",    # pywebview js-api proxy
    "onnxruntime",     # imported lazily when the recognition backend starts
]

# --- bundled web assets (designer + runner; NO hub) --------------------------
# Unlike apps_build.spec this omits apps/web/hub: the Hub is not analysed and
# its HTML is not shipped, so the palette of this build is Designer + Runner.
_web_src = os.path.join(ROOT, "apps", "web")
web_datas = [
    (os.path.join(_web_src, "shared"), os.path.join("web", "shared")),
    (os.path.join(_web_src, "wf"), os.path.join("web", "wf")),
    (os.path.join(_web_src, "runner"), os.path.join("web", "runner")),
    (os.path.join(ROOT, "assets", "ocr", "ppocr_v5_mobile"),
     os.path.join("assets", "ocr", "ppocr_v5_mobile")),
]

# --- build toolchain, so the Designer's Build EXE button works --------------
# The Designer shells out to packaging/build_runner.py, which reads this spec,
# the entry it analyses, the icon guard, and two src modules. That script
# locates the checkout from its own path, so those source files must sit inside
# the bundle with the same layout. vendor/ stays external.
# Destinations are directories, not file paths: PyInstaller treats a destination
# whose basename equals the source file's name as a directory and nests the file
# inside it, so "packaging/build_runner.py" would land one level too deep.
# Do not copy ``src/__init__.py`` as data: a physical ``_macro2k/src`` package
# would shadow the compiled package in the exe and make ``src.runner_update``
# impossible to import from the frozen Designer.
web_datas += [
    (os.path.join(SPECPATH, "build_runner.py"), "packaging"),
    (os.path.join(SPECPATH, "runner_build.spec"), "packaging"),
    (os.path.join(SPECPATH, "entry_runner_single.py"), "packaging"),
    (os.path.join(SPECPATH, "check_icons.py"), "packaging"),
    (os.path.join(SPECPATH, "app.ico"), "packaging"),
    # Same layout the source checkout has, so runner_build.spec finds
    # apps/web/{shared,runner}. Copy those two only — a wholesale apps/web copy
    # would drag the Hub's HTML into a build that deliberately excludes it.
    (os.path.join(_web_src, "shared"), os.path.join("apps", "web", "shared")),
    (os.path.join(_web_src, "runner"), os.path.join("apps", "web", "runner")),
]


# --- exclude the world we don't ship -----------------------------------------
excludes = [
    "PySide6", "shiboken6", "PyQt5", "PyQt6", "qtawesome",
    "torch", "torchvision", "torchaudio",
    "scipy", "matplotlib", "sympy", "sklearn", "skimage",
    "paddle", "paddleocr", "paddlex", "easyocr", "pytesseract", "onnx",
    "tkinter", "IPython", "notebook", "jupyter", "pytest",
]

_common = dict(
    pathex=[ROOT, APPS],
    binaries=binaries,
    hiddenimports=hiddenimports,
    excludes=excludes,
    hookspath=[],
    runtime_hooks=[],
    noarchive=False,
)

# ── Macro2k.exe (Designer default + Runner) ──────────────────────────────
a_designer = Analysis(
    [os.path.join(ROOT, "packaging", "entry_studio.py")],
    datas=datas + web_datas,
    **_common,
)
pyz_designer = PYZ(a_designer.pure)
exe_designer = EXE(
    pyz_designer, a_designer.scripts, [],
    exclude_binaries=True, name="Macro2k",
    console=False, disable_windowed_traceback=False,
    contents_directory="_macro2k",
    icon=ICON,
    version=version_info,
)
coll_designer = COLLECT(
    exe_designer, a_designer.binaries, a_designer.datas,
    name="Macro2k",
)
